name: Publish

on:
  push:
    branches: '*'

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          git_branch=${GITHUB_REF##*/}
          release_name="NxCertDump-$git_branch-${{ matrix.target }}"
          # Build everything
          dotnet publish NxCertDump/NxCertDump.csproj --framework netcoreapp3.1 --runtime "${{ matrix.target }}" -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"
      - name: Publish
        uses: "johnwbyrd/update-release@v1.0.0"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          release: "Latest Build"
          prerelease: true
          files: NxCertDump-*
